const $ = s => document.querySelector(s);
const view = $('#view');
let currentView = 'overview';
let chosenSchool = 'DEMO-E01';
let chosenProject = 'DEMO-R01';
let schools = [];
let projects = [];
let neisSchools = [];
let chosenReference = null;
let isDemo = true;
const year = () => Number($('#year').value);
const fmt = (n, digits=0) => n == null || !Number.isFinite(n) ? '자료 부족' : Number(n).toLocaleString('ko-KR',{maximumFractionDigits:digits,minimumFractionDigits:digits});
const kstDate = value => value ? new Date(value).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}) : '미기록';
const coverage = (recorded,checked,total) => checked===0?'미조회':`${recorded}건 응답 / ${checked}/${total} 조회${recorded===0&&checked===total?' · 제공행 없음':''}`;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api = async url => {
  if (window.schoolEnergySnapshot) {
    if (!Object.prototype.hasOwnProperty.call(window.schoolEnergySnapshot, url)) throw Error('게시된 자료에 없는 조회입니다.');
    return window.schoolEnergySnapshot[url];
  }
  const r = await fetch(url); const x = await r.json(); if(!r.ok) throw Error(x.error || '요청 실패'); return x;
};
const card = (label,value,unit,sub='') => `<article class="card"><div class="metric-label">${label}</div><div class="metric">${value} <small>${unit}</small></div><div class="metric-sub">${sub}</div></article>`;
const pill = (text,type='ok') => `<span class="pill ${type}">${text}</span>`;
const schoolSelect = () => `<div class="selector-line"><label for="school-select">학교 선택</label><select id="school-select">${schools.map(s=>`<option value="${esc(s.id)}" ${s.id===chosenSchool?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div>`;
function lineChart(values){
  const good=values.filter(x=>x!=null),max=Math.max(1,...good),min=0;
  const p=values.map((v,i)=>v==null?null:[34+i*680/Math.max(1,values.length-1),190-(v-min)/(max-min)*158]);
  const segments=[];let run=[];for(const point of p){if(point)run.push(point);else if(run.length){segments.push(run);run=[]}}if(run.length)segments.push(run);
  return `<svg class="chart" viewBox="0 0 750 218" role="img" aria-label="월별 에너지 사용 추이"><line x1="34" y1="190" x2="720" y2="190"/><line x1="34" y1="110" x2="720" y2="110"/><line x1="34" y1="32" x2="720" y2="32"/><text x="0" y="36">${fmt(max/1000,0)}k</text><text x="0" y="194">0</text>${segments.map(s=>`<polyline points="${s.map(x=>x.join(',')).join(' ')}"/>`).join('')}${p.map(x=>x?`<circle cx="${x[0]}" cy="${x[1]}" r="3"/>`:'' ).join('')}</svg>`;
}
async function overview(){
  const [data,screens,candidateSummary,districtSeries,priorityData]=await Promise.all([api(`/api/overview?year=${year()}`),api(`/api/screening?year=${year()}`),api(`/api/candidate-energy-summary?year=${year()}`),api(`/api/candidate-energy-district-series?year=${year()}`),api(`/api/candidate-priority?year=${year()}`)]);
  const sorted=[...data.schools].sort((a,b)=>(b.energy_kwh||-1)-(a.energy_kwh||-1));
  const totals=await Promise.all(schools.slice(0,1).map(s=>api(`/api/schools/${s.id}?year=${year()}`)));
  const sample=totals[0]?.series.filter(x=>x.month.startsWith(String(year())))||[];
  const observed=candidateSummary.observed_totals||{};
  const reference=candidateSummary.electricity_reference_factor;
  const kpis=isDemo?`${card('관리학교',fmt(data.school_count),'개교',`연간 완결 ${data.complete_school_count}개교`)}${card('연간 에너지',data.complete_school_count?fmt(data.energy_kwh/1000000,2):'—','GWh','완결 학교만 합산')}${card('연간 탄소배출',data.complete_school_count?fmt(data.kgco2e/1000,1):'—','tCO₂e','합성 배출계수 기준')}${card('태양광 발전',fmt(data.solar_kwh/1000,1),'MWh','계측 발전량 합계')}`:`${card('조회 지번 전기',observed.electricity_kwh==null?'—':fmt(observed.electricity_kwh/1000,1),'MWh',`${esc(candidateSummary.month||'조회 전')} · ${fmt(observed.electricity_parcels||0)}개 지번`)}${card('조회 지번 가스',observed.gas_kwh==null?'—':fmt(observed.gas_kwh/1000,1),'MWh',`${esc(candidateSummary.month||'조회 전')} · ${fmt(observed.gas_parcels||0)}개 지번`)}${card('전기분 탄소 참고치',observed.electricity_reference_kgco2e==null?'—':fmt(observed.electricity_reference_kgco2e/1000,2),'tCO₂e',observed.electricity_kwh==null?'전기 응답 없음':reference?`${fmt(reference.factor_value,4)} kgCO₂e/kWh 적용`:'참조계수 없음')}${card('확정 학교',fmt(data.complete_school_count),'개교','학교 합계·가스 탄소 검증 전')}`;
  view.innerHTML=`${!isDemo&&data.school_count===0?`<div class="callout">나이스 학교 목록에 공식 주소정보와 추가 검증 지번 후보를 연결해 국토교통부 건물에너지 API를 조회했습니다. 아래 조회 현황은 지번 후보별 원자료이며, 학교별 공식 합계는 시설대장과 계량 범위 검증 후 산정합니다.${data.last_refresh?` 최근 갱신 점검: ${esc(kstDate(data.last_refresh.finished_at))} KST (${data.last_refresh.status==='complete'?'완료':'오류'}).`:''}</div><br>`:''}<div class="grid kpis">${kpis}</div>
  <div class="grid columns"><div class="grid"><article class="card"><div class="section-head"><h2>월별 에너지 추이</h2><span class="legend">${esc(schools[0]?.name||'학교 없음')} · 전기 + 가스</span></div>${sample.length?`${lineChart(sample.map(x=>x.total_kwh))}<div class="bar-labels"><span>1월</span><span>6월</span><span>12월</span></div>`:'<div class="empty">학교·지번 계측자료 연결 전입니다.</div>'}</article>
  <article class="card"><div class="section-head"><h2>학교별 현황</h2><span class="hint">완결 학교만 연간 지표 표시</span></div>${sorted.length?`<div class="table-wrap"><table><thead><tr><th>학교</th><th>지역</th><th>에너지</th><th>탄소</th><th>데이터</th></tr></thead><tbody>${sorted.map(s=>`<tr><td><button class="link" data-school="${esc(s.id)}">${esc(s.name)}</button></td><td>${esc(s.district)}</td><td>${s.energy_kwh==null?'—':fmt(s.energy_kwh/1000,1)+' MWh'}</td><td>${s.kgco2e==null?'—':fmt(s.kgco2e/1000,1)+' t'}</td><td>${s.data_quality==='complete'?pill('완결'):pill(`${s.complete_months}/12개월`,'bad')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">분석용 학교 원장 등록 전입니다. 나이스 참조목록은 데이터 검증 메뉴에서 확인할 수 있습니다.</div>'}</article></div>
  <div class="grid"><article class="card"><div class="section-head"><h2>분석 검토</h2><span class="hint">자동 결정 아님</span></div>${screens.filter(s=>s.grade!=='관찰').sort((a,b)=>['우선검토','검토','데이터 확인'].indexOf(a.grade)-['우선검토','검토','데이터 확인'].indexOf(b.grade)).map(s=>`<div class="row"><div><strong>${esc(s.name)}</strong><div class="metric-sub">${esc(s.reasons[0])}</div></div>${pill(esc(s.grade),s.grade==='우선검토'?'bad':'dim')}</div>`).join('')}<div class="callout">관찰 결과는 시설 담당자의 현장 확인과 예산 검토를 위한 참고자료입니다.</div></article><article class="card"><div class="section-head"><h2>데이터 신뢰도</h2></div><div class="metric">${data.complete_school_count}<small> / ${data.school_count} 개교</small></div><div class="metric-sub">12개월 모두 매칭·계측·계수 확인</div><div class="bars">${data.schools.map(s=>`<div class="bar ${s.complete_months===12?'highlight':''}" title="${esc(s.name)}" style="height:${Math.max(5,s.complete_months/12*100)}%"></div>`).join('')}</div><div class="bar-labels"><span>학교별 완결률</span><span>100%</span></div></article></div></div>`;
  if (!isDemo && priorityData.school_count) {
    const leaders=priorityData.schools.filter(s=>s.intensity_review_rank)
      .sort((a,b)=>a.intensity_review_rank-b.intensity_review_rank).slice(0,5);
    view.querySelector('.grid.kpis').insertAdjacentHTML('beforeend',card('원단위 검토 후보',fmt(priorityData.intensity_review_count),'개교','잠정 현장검토 · 투자순위 보류'));
    view.querySelector('.grid.kpis').insertAdjacentHTML('afterend',`<article class="card priority-preview"><div class="section-head"><h2>면적당 에너지·탄소 기반 현장검토 후보</h2><span class="hint">${year()}년 · ${priorityData.intensity_review_count}개교 잠정 비교</span></div><p>같은 학교급의 관측 kWh/㎡와 전기분 탄소 참고 kgCO₂e/㎡를 각 50% 반영한 자료확인 순서입니다. 가스 탄소와 시설 상태는 포함되지 않았으며, 시설개선 투자 우선순위는 ${esc(priorityData.investment_status)}입니다.</p>${leaders.length?`<div class="table-wrap"><table><thead><tr><th>검토 순서</th><th>학교</th><th>관측 kWh/㎡</th><th>전기분 참고 kgCO₂e/㎡</th></tr></thead><tbody>${leaders.map(s=>`<tr><td>${s.intensity_review_rank}</td><td><button class="link" data-overview-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${fmt(s.observed_kwh_per_registry_m2,1)}</td><td>${fmt(s.electricity_reference_kgco2e_per_registry_m2,2)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">이 연도에는 원단위 비교에 필요한 자료가 부족합니다.</div>'}<button class="action" id="priority-open">분석 근거와 전체 순서 보기</button></article><br>`);
    $('#priority-open').addEventListener('click',()=>switchView('priority'));
    document.querySelectorAll('[data-overview-priority-school]').forEach(b=>b.addEventListener('click',()=>{chosenReference=b.dataset.overviewPrioritySchool;switchView('school')}));
  }
  if (!isDemo && candidateSummary.source) {
    const listed=candidateSummary.schools;
    const matched=listed.filter(s=>s.candidate_parcels).length;
    const electric=listed.filter(s=>s.electricity_recorded).length;
    const gas=listed.filter(s=>s.gas_recorded).length;
    const factorNote=reference?`전기분 탄소 참고치 = 조회된 전기 kWh × ${fmt(reference.factor_value,4)} kgCO₂e/kWh (온실가스종합정보센터 ${esc(reference.approval_year)}년 승인, ${esc(reference.data_years)}년 평균). 사용연도 적용기준은 미확정이며 가스 탄소는 포함하지 않습니다.`:'전력 배출계수 참조자료가 없어 전기분 탄소를 계산하지 않았습니다.';
    const monthly=`<article class="card"><div class="section-head"><h2>${year()}년 월별 에너지·전기분 탄소</h2><span class="hint">서로 다른 후보 지번의 API 응답 소계</span></div><div class="table-wrap"><table><thead><tr><th>월</th><th>전기 kWh</th><th>가스 kWh</th><th>전기분 탄소 참고 kgCO₂e</th><th>전기/가스 응답 지번</th></tr></thead><tbody>${districtSeries.months.map(m=>`<tr><td>${esc(m.month)}</td><td>${m.observed_electricity_kwh==null?'—':fmt(m.observed_electricity_kwh)}</td><td>${m.observed_gas_kwh==null?'—':fmt(m.observed_gas_kwh)}</td><td>${m.observed_electricity_reference_kgco2e==null?'—':fmt(m.observed_electricity_reference_kgco2e,1)}</td><td>전기 ${coverage(m.electricity_parcels,m.electricity_checked,m.candidate_parcels)}<br>가스 ${coverage(m.gas_parcels,m.gas_checked,m.candidate_parcels)}</td></tr>`).join('')}</tbody></table></div><div class="callout">조회된 지번만 더한 값입니다. 미조회와 조회 후 제공행 없음을 구분합니다. 응답이 없는 지번은 0으로 취급하지 않으며, 학교 공식 총량이 아닙니다. ${factorNote}</div></article><br>`;
    const provisional=`<article class="card"><div class="section-head"><h2>학교별 조회 지번 에너지·전기분 탄소</h2><span class="hint">${esc(candidateSummary.month||'조회 전')} · 주소 지번 후보 기준</span></div><div class="grid summary-grid">${card('주소 일치 학교',fmt(matched),'개교',`${fmt(listed.length)}개교 중 지번 후보 확보`)}${card('전기 응답 학교',fmt(electric),'개교','후보 지번 중 한 곳 이상 응답')}${card('가스 응답 학교',fmt(gas),'개교','후보 지번 중 한 곳 이상 응답')}</div><div class="table-wrap"><table><thead><tr><th>학교</th><th>전기 관측 소계 kWh</th><th>가스 관측 소계 kWh</th><th>전기분 탄소 참고 kgCO₂e</th><th>응답 지번 전기/가스</th><th>검토사항</th></tr></thead><tbody>${listed.map(s=>`<tr><td><button class="link" data-reference-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${s.observed_electricity_kwh==null?'—':fmt(s.observed_electricity_kwh)}</td><td>${s.observed_gas_kwh==null?'—':fmt(s.observed_gas_kwh)}</td><td>${s.observed_electricity_reference_kgco2e==null?'—':fmt(s.observed_electricity_reference_kgco2e,1)}</td><td>전기 ${coverage(s.electricity_recorded,s.electricity_checked,s.candidate_parcels)}<br>가스 ${coverage(s.gas_recorded,s.gas_checked,s.candidate_parcels)}</td><td>${s.shared_parcels?'공유 지번 ':''}${s.review_issues?'API 응답 불일치 ':''}${!s.candidate_parcels?'주소 미매칭':''}</td></tr>`).join('')}</tbody></table></div><div class="callout">각 행은 학교에 연결된 후보 지번의 관측 소계입니다. 응답이 누락된 지번이 있고, 공유 지번은 여러 학교 행에 나타날 수 있습니다. 상단 관내 수치는 같은 지번을 한 번만 합산했습니다. 시설대장과 계량 범위 검증 전에는 학교 총사용량이나 총탄소량으로 해석하지 않습니다. ${factorNote}</div></article>`;
    view.querySelector('.grid.columns').remove();
    view.insertAdjacentHTML('beforeend',monthly+provisional);
    document.querySelectorAll('[data-reference-school]').forEach(b=>b.addEventListener('click',()=>{chosenReference=b.dataset.referenceSchool;switchView('school')}));
  }
  document.querySelectorAll('[data-school]').forEach(b=>b.addEventListener('click',()=>{chosenSchool=b.dataset.school;switchView('school')}));
}
async function priority(){
  const d=await api(`/api/candidate-priority?year=${year()}`);
  if (!d.school_count) {
    const screens=await api(`/api/screening?year=${year()}`);
    view.innerHTML=`<article class="card"><h2>시설개선 검토 시연</h2><div class="callout">시연용 합성 학교의 유사학교 비교·기상보정·시설연식을 조합한 현장조사 등급입니다. 실제 교육지원청 투자 순위가 아닙니다.</div><div class="table-wrap"><table><thead><tr><th>학교</th><th>검토등급</th><th>분석 신뢰도</th><th>근거</th></tr></thead><tbody>${screens.map(s=>`<tr><td>${esc(s.name)}</td><td>${pill(esc(s.grade),s.grade==='우선검토'?'bad':'dim')}</td><td>${esc(s.confidence)}</td><td>${esc(s.reasons.join(' · '))}</td></tr>`).join('')}</tbody></table></div></article>`;
    return;
  }
  const ranked=d.schools.filter(s=>s.review_rank);
  const blocked=d.schools.filter(s=>!s.review_rank);
  const factor=d.electricity_reference_factor;
  view.innerHTML=`<div class="grid summary-grid">${card('나이스 참조학교',fmt(d.school_count),'개교','실증학교 원장 검증 전')}${card('12개월 후보 응답 완결',fmt(d.profile_complete_count),'개교','공유 지번·API 불일치 제외')}${card('시설투자 우선순위',esc(d.investment_status),'','시설·면적·계량 범위 검증 전')}</div>
    <article class="card"><div class="section-head"><h2>잠정 현장확인 순서</h2><span class="hint">${year()}년 · ${esc(d.source||'주소 지번 후보 없음')}</span></div><div class="callout">${esc(d.method)}. 순서는 사용 규모에 따른 <strong>현장확인 순서</strong>이며 에너지 효율, 설비 노후, 절감 가능량, 시설개선 투자 순위가 아닙니다. 후보 지번에는 학교 외 사용처가 포함될 수 있습니다.</div>${ranked.length?`<div class="table-wrap"><table><thead><tr><th>순서</th><th>학교</th><th>학교급</th><th>전기 관측 MWh/년</th><th>가스 관측 MWh/년</th><th>합계 관측 MWh/년</th><th>전기분 탄소 참고 tCO₂e</th><th>다음 조치</th></tr></thead><tbody>${ranked.map(s=>`<tr><td>${s.review_rank}</td><td><button class="link" data-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${esc(s.level)}</td><td>${fmt(s.annual_electricity_kwh/1000,1)}</td><td>${fmt(s.annual_gas_kwh/1000,1)}</td><td><strong>${fmt(s.annual_observed_kwh/1000,1)}</strong></td><td>${s.annual_electricity_reference_kgco2e==null?'—':fmt(s.annual_electricity_reference_kgco2e/1000,2)}</td><td>${esc(s.next_step)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">이 연도에는 12개월 전기·가스 응답이 완결된 후보가 없습니다. 미조회 또는 제공행 없음은 사용량 0으로 간주하지 않습니다.</div>'}<div class="callout">전기분 탄소 참고치는 ${factor?`${fmt(factor.factor_value,4)} kgCO₂e/kWh (${esc(factor.approval_year)}년 승인, ${esc(factor.data_years)}년 평균)`:'참조계수 없음'} 기준입니다. 사용연도 적용기준은 미확정이며 가스 탄소는 포함하지 않습니다. 연간 전기+가스 합계는 관측된 후보 지번의 사용량 규모를 나타내며, 학교 전체 계량 범위를 뜻하지 않습니다.</div></article><br>
    <article class="card"><div class="section-head"><h2>시설투자 판정에 필요한 검증</h2><span class="hint">선정 후 교육지원청 자료 연계</span></div><div class="facts">${d.investment_blockers.map(x=>`<div class="fact"><span>필요 자료·검증</span><strong>${esc(x)}</strong></div>`).join('')}</div><div class="callout">이 자료가 채워지면 학교급·연면적별 원단위, 전년 및 기상보정 추세, 시설 연식과 기존 사업효과를 함께 검토합니다. 설비 노후가 사용량 증가의 원인이라고 자동 판정하지 않습니다.</div></article><br>
    <article class="card"><div class="section-head"><h2>자료 보완 대상</h2><span class="hint">${blocked.length}개교 · 투자순위 제외</span></div>${blocked.length?`<div class="table-wrap"><table><thead><tr><th>학교</th><th>전기 완결</th><th>가스 완결</th><th>보완 사유</th><th>다음 조치</th></tr></thead><tbody>${blocked.map(s=>`<tr><td><button class="link" data-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${s.complete_months.electricity}/12개월</td><td>${s.complete_months.gas}/12개월</td><td>${esc(s.blockers.join(' · '))}</td><td>${esc(s.next_step)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">현재 보완 대상이 없습니다.</div>'}</article>`;
  const areaCandidates=d.schools.filter(s=>s.registry_area_candidate_m2!=null)
    .sort((a,b)=>a.name.localeCompare(b.name,'ko'));
  const noRegistry=d.schools.filter(s=>s.registry_title_rows===0&&s.registry_recap_rows===0)
    .sort((a,b)=>a.name.localeCompare(b.name,'ko'));
  view.querySelector('.grid.summary-grid').insertAdjacentHTML('afterend',
    `<article class="card"><div class="section-head"><h2>건축물대장 기준 잠정 원단위</h2><span class="hint">${areaCandidates.length}개교 면적 후보 · ${d.provisional_intensity_count}개교 원단위</span></div><div class="callout">지번별 총괄표제부 연면적을 우선 사용하고, 총괄표제부가 없으면 동별 표제부 연면적을 합산합니다. 여러 학교가 공유하거나 건물 소속이 불명확한 지번은 보류합니다. 학교 시설대장과 계량 범위를 확인하기 전의 잠정값이며 시설투자 순위에 반영하지 않습니다.</div>${areaCandidates.length?`<div class="table-wrap"><table><thead><tr><th>학교</th><th>잠정 연면적 후보 ㎡</th><th>면적 출처</th><th>관측 에너지 kWh/㎡</th><th>상태</th></tr></thead><tbody>${areaCandidates.map(s=>`<tr><td><button class="link" data-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${fmt(s.registry_area_candidate_m2,2)}</td><td>${esc(s.registry_area_source||'자료 확인 필요')}</td><td>${fmt(s.observed_kwh_per_registry_m2,1)}</td><td>${esc(s.registry_area_status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">이 연도에 면적과 12개월 에너지가 함께 확인된 후보가 없습니다.</div>'}</article><br><article class="card"><div class="section-head"><h2>건축물대장 면적 자료 점검</h2><span class="hint">총괄표제부 ${d.registry_recap_school_count}개교 · 동별만 ${d.registry_title_only_school_count}개교 · 후보 지번 미조회 ${d.registry_no_row_school_count}개교</span></div><div class="callout">현재 연결한 지번으로 총괄표제부·동별 표제부가 조회되지 않은 학교입니다. 이는 건축물대장 자체의 부존재나 면적 0㎡를 뜻하지 않습니다. 과거·부속 지번, 폐쇄말소대장, 사용승인 및 교육청 시설대장을 대조해야 합니다.</div>${noRegistry.length?`<div class="table-wrap"><table><thead><tr><th>후보 지번에서 미조회된 학교</th><th>주소 지번 후보</th><th>다음 확인</th></tr></thead><tbody>${noRegistry.map(s=>`<tr><td><button class="link" data-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${s.candidate_parcels}건</td><td>${s.area_research?areaResearchLink(s.area_research):"학교 시설대장·현재 지번·사용승인 확인"}</td></tr>`).join('')}</tbody></table></div>`:''}</article><br>`);
  const intensityRanked=d.schools.filter(s=>s.intensity_review_rank)
    .sort((a,b)=>a.intensity_review_rank-b.intensity_review_rank);
  view.querySelector('.grid.summary-grid').insertAdjacentHTML('afterend',
    `<article class="card"><div class="section-head"><h2>원단위 기반 시설개선 현장검토 후보</h2><span class="hint">${d.intensity_review_count}개교 · 잠정 순서</span></div><div class="callout">${esc(d.intensity_review_method)}. 전기분 탄소는 승인 연도와 사용연도 적용을 확정하지 않은 참고계수로 계산했고 가스 탄소는 제외했습니다. 건축물대장 면적과 지번별 에너지의 학교 계량 범위가 아직 확정되지 않아 시설개선 투자 우선순위나 설비 원인 판정으로 사용하지 않습니다. 계획면적만 있는 학교는 순서에서 제외합니다.</div>${intensityRanked.length?`<div class="table-wrap"><table><thead><tr><th>검토 순서</th><th>학교</th><th>학교급</th><th>관측 에너지 kWh/㎡</th><th>전기분 탄소 참고 kgCO₂e/㎡</th><th>동급 중앙값 대비 에너지</th><th>잠정 점수</th></tr></thead><tbody>${intensityRanked.map(s=>`<tr><td>${s.intensity_review_rank}</td><td><button class="link" data-priority-school="${esc(s.school_code)}">${esc(s.name)}</button></td><td>${esc(s.level)}</td><td>${fmt(s.observed_kwh_per_registry_m2,1)}</td><td>${fmt(s.electricity_reference_kgco2e_per_registry_m2,2)}</td><td>${s.energy_peer_median_kwh_per_m2?fmt((s.observed_kwh_per_registry_m2/s.energy_peer_median_kwh_per_m2-1)*100,1)+'%':'—'}</td><td>${fmt(s.intensity_review_score,1)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">이 연도에는 원단위 비교에 필요한 12개월 자료와 건축물대장 면적이 함께 확보된 학교가 부족합니다.</div>'}</article><br>`);
  document.querySelectorAll('[data-priority-school]').forEach(b=>b.addEventListener('click',()=>{chosenReference=b.dataset.prioritySchool;switchView('school')}));
}
function areaResearchLink(research){
  if(!research)return '';
  const source=research.source_url?.startsWith('https://')
    ?` <a href="${esc(research.source_url)}" target="_blank" rel="noopener noreferrer">근거</a>`:'';
  return `<div class="metric-sub">${esc(research.observed_on)} 조사 · ${esc(research.finding)}${source}</div><div class="metric-sub">다음 확인: ${esc(research.next_check)}</div>`;
}
function buildingRegistryCard(data, area){
  const parcels=data.parcels||[];
  const rows=parcels.flatMap(p=>p.records.map(r=>({parcel:p.parcel_key,...r})));
  const empty=parcels.filter(p=>!p.records.length);
  const sourceLink=area?.registry_area_source_url?.startsWith('https://')
    ?` <a href="${esc(area.registry_area_source_url)}" target="_blank" rel="noopener noreferrer">근거 문서</a>`:'';
  return `<br><article class="card"><div class="section-head"><h2>건축물대장 연면적 후보</h2><span class="hint">총괄표제부·동별 표제부 · 지번 조회</span></div><div class="callout">${area?.registry_area_candidate_m2!=null?`잠정 연면적 <strong>${fmt(area.registry_area_candidate_m2,2)}㎡</strong> · ${esc(area.registry_area_status)}${sourceLink}.`:`잠정 면적 산정 보류: ${esc(area?.registry_area_status||'자료 확인 필요')}.`} 시설대장과 계량 범위를 확인하기 전에는 학교 확정 연면적이나 효율 비교에 사용하지 않습니다.</div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>지번키</th><th>대장 항목</th><th>건물·동 명칭</th><th>연면적 ㎡</th><th>사용승인일</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.parcel)}</td><td>${r.operation==='getBrRecapTitleInfo'?'총괄표제부':'동별 표제부'}</td><td>${esc([r.building_name,r.dong_name].filter(x=>x&&x.trim()).join(' / ')||'명칭 없음')}</td><td>${r.total_area_m2==null?'—':fmt(r.total_area_m2,2)}</td><td>${esc(r.approved_day||'—')}</td></tr>`).join('')}</tbody></table></div>`:''}${empty.map(p=>`<div class="row"><span>${esc(p.parcel_key)}</span><strong>${p.checks.length===2?'현재 후보 지번의 대장 API 미조회':'조회 전'}</strong></div>`).join('')}<div class="callout">총괄표제부와 동별 표제부는 같은 건물을 중복해 나타낼 수 있어 합산하지 않습니다. 총괄표제부가 있으면 동별 표제부와 중복 합산하지 않습니다. 다른 학교 건물이 포함된 공유 지번은 보류합니다.</div></article>`;
}
async function school(){
  if (!schools.length) {
    if (!neisSchools.length) { view.innerHTML='<article class="card"><h2>실증학교 자료 대기</h2></article>'; return; }
    const selected=neisSchools.find(x=>x.school_code===chosenReference)||neisSchools[0];
    const parcelCandidates=(await api('/api/parcel-candidates')).filter(x=>x.school_code===selected.school_code);
    const [provisional,series,registry,priorityReport]=await Promise.all([
      api(`/api/candidate-energy-detail?school_code=${encodeURIComponent(selected.school_code)}&year=${year()}`),
      api(`/api/candidate-energy-series?school_code=${encodeURIComponent(selected.school_code)}&year=${year()}`),
      api(`/api/candidate-building-registry?school_code=${encodeURIComponent(selected.school_code)}`),
      api(`/api/candidate-priority?year=${year()}`)]);
    const electricRows=provisional.parcels.filter(p=>p.electricity_kwh!=null);
    const gasRows=provisional.parcels.filter(p=>p.gas_kwh!=null);
    const electricKwh=electricRows.length?electricRows.reduce((sum,p)=>sum+p.electricity_kwh,0):null;
    const gasKwh=gasRows.length?gasRows.reduce((sum,p)=>sum+p.gas_kwh,0):null;
    const reference=provisional.electricity_reference_factor;
    const electricCarbon=electricKwh!=null&&reference?electricKwh*reference.factor_value:null;
    const factorNote=reference?`전기분 탄소 참고치 = 조회된 전기 kWh × ${fmt(reference.factor_value,4)} kgCO₂e/kWh (${esc(reference.approval_year)}년 승인, ${esc(reference.data_years)}년 평균). 가스 탄소와 학교 총탄소는 포함하지 않습니다.`:'전력 배출계수 참조자료가 없어 전기분 탄소를 계산하지 않았습니다.';
    view.innerHTML=`<div class="selector-line"><label for="reference-school-select">학교 선택</label><select id="reference-school-select">${neisSchools.map(x=>`<option value="${esc(x.school_code)}" ${x.school_code===selected.school_code?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="grid summary-grid">${card('조회 지번 전기',electricKwh==null?'—':fmt(electricKwh),'kWh',`${esc(provisional.month||'조회 전')} · ${electricRows.length}/${provisional.parcels.length}개 지번`)}${card('조회 지번 가스',gasKwh==null?'—':fmt(gasKwh),'kWh',`${esc(provisional.month||'조회 전')} · ${gasRows.length}/${provisional.parcels.length}개 지번`)}${card('전기분 탄소 참고치',electricCarbon==null?'—':fmt(electricCarbon,1),'kgCO₂e','학교 총탄소 아님')}</div><article class="card"><div class="section-head"><h2>학교 기본정보</h2><span class="hint">나이스 조회 결과</span></div><div class="facts"><div class="fact"><span>학교명</span><strong>${esc(selected.name)}</strong></div><div class="fact"><span>학교코드</span><strong>${esc(selected.school_code)}</strong></div><div class="fact"><span>학교급</span><strong>${esc(selected.level)}</strong></div><div class="fact"><span>주소</span><strong>${esc(selected.address)}</strong></div><div class="fact"><span>관할</span><strong>${esc(selected.agency)}</strong></div></div><div class="callout">위 수치는 학교에 연결된 후보 지번의 API 응답 소계입니다. 시설대장과 계량 범위를 확인하기 전에는 학교 총사용량으로 확정하지 않습니다. ${factorNote}</div></article>`;
    view.insertAdjacentHTML('beforeend', `<br><article class="card"><div class="section-head"><h2>학교 지번 후보</h2><span class="hint">주소정보 연계 · 미확정</span></div>${parcelCandidates.length?parcelCandidates.map(x=>`<div class="row"><div><strong>${esc(x.jibun_address||x.parcel_key)}</strong><div class="metric-sub">${esc(x.parcel_key)} · ${esc(x.source)}</div>${x.match_evidence?`<div class="metric-sub">${esc(x.match_evidence)}</div>`:''}</div>${pill(x.shared_candidate?'공유 후보':x.status==='pending'?'검토 대기':'검토 기록','dim')}</div>`).join(''):'<div class="empty">도로명주소에서 지번 후보를 아직 조회하지 않았습니다.</div>'}<div class="callout">학교의 전체 부지와 계량기 범위는 시설자료로 대조한 뒤 확정합니다.</div></article>`);
    const areaResearch=priorityReport.schools.find(x=>x.school_code===selected.school_code)?.area_research;
    view.insertAdjacentHTML('beforeend', buildingRegistryCard(registry,
      priorityReport.schools.find(x=>x.school_code===selected.school_code)));
    if(areaResearch)view.insertAdjacentHTML('beforeend', `<article class="card"><div class="section-head"><h2>연면적 자료조사</h2><span class="hint">면적 산정에 미반영</span></div>${areaResearchLink(areaResearch)}</article>`);
    view.insertAdjacentHTML('beforeend', `<br><article class="card"><div class="section-head"><h2>후보 지번별 에너지·전기분 탄소</h2><span class="hint">${esc(provisional.month||'조회 전')} · 국토교통부 건물에너지정보</span></div>${provisional.parcels.length?`<div class="table-wrap"><table><thead><tr><th>지번주소</th><th>전기 kWh</th><th>가스 kWh</th><th>전기분 탄소 참고 kgCO₂e</th><th>검토사항</th></tr></thead><tbody>${provisional.parcels.map(p=>`<tr><td>${esc(p.jibun_address)}</td><td>${p.electricity_kwh==null?'—':fmt(p.electricity_kwh)} ${p.electricity_status==='missing'?'(제공행 없음)':''}</td><td>${p.gas_kwh==null?'—':fmt(p.gas_kwh)} ${p.gas_status==='missing'?'(제공행 없음)':''}</td><td>${p.electricity_reference_kgco2e==null?'—':fmt(p.electricity_reference_kgco2e,1)}</td><td>${p.shared_candidate?'공유 지번 ':''}${p.issue_code?'API 응답 불일치':''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조회할 지번 후보가 없습니다.</div>'}<div class="callout">지번별 원자료와 전기분 참고 환산입니다. 관련지번에 학교 외 사용처가 있을 수 있습니다. ${factorNote}</div></article>`);
    view.insertAdjacentHTML('beforeend', `<br><article class="card"><div class="section-head"><h2>${year()}년 후보 지번 월별 에너지·전기분 탄소</h2><span class="hint">전기 응답 ${series.months.filter(x=>x.observed_electricity_kwh!=null).length}/12개월 · 가스 응답 ${series.months.filter(x=>x.observed_gas_kwh!=null).length}/12개월</span></div><div class="table-wrap"><table><thead><tr><th>월</th><th>전기 관측 소계 kWh</th><th>가스 관측 소계 kWh</th><th>전기분 탄소 참고 kgCO₂e</th><th>응답 지번 전기/가스</th></tr></thead><tbody>${series.months.map(x=>`<tr><td>${esc(x.month)}</td><td>${x.observed_electricity_kwh==null?'—':fmt(x.observed_electricity_kwh)}</td><td>${x.observed_gas_kwh==null?'—':fmt(x.observed_gas_kwh)}</td><td>${x.observed_electricity_reference_kgco2e==null?'—':fmt(x.observed_electricity_reference_kgco2e,1)}</td><td>전기 ${coverage(x.electricity_recorded,x.electricity_checked,x.candidate_parcels)}<br>가스 ${coverage(x.gas_recorded,x.gas_checked,x.candidate_parcels)}</td></tr>`).join('')}</tbody></table></div><div class="callout">응답 지번만 합산했습니다. 누락 지번은 0으로 채우지 않으며, 이 값은 학교 공식 사용량이 아닙니다. ${factorNote}</div></article>`);
    $('#reference-school-select').addEventListener('change',e=>{chosenReference=e.target.value;render()});
    return;
  }
  const d=await api(`/api/schools/${chosenSchool}?year=${year()}`),s=d.school;
  const recent=d.series.filter(x=>x.month.startsWith(String(year()))),complete=recent.filter(x=>x.complete);
  const electric=complete.reduce((a,x)=>a+x.electricity_kwh,0),gas=complete.reduce((a,x)=>a+x.gas_kwh,0);
  view.innerHTML=`${schoolSelect()}<div class="grid summary-grid">${card('연간 전기',recent.length===12&&complete.length===12?fmt(electric/1000,1):'—','MWh',`${complete.length}/12개월 확인`)}${card('연간 가스',recent.length===12&&complete.length===12?fmt(gas/1000,1):'—','MWh','가스 원자료 kWh')}${card('유사학교 대비',d.peer.status==='ok'?((d.peer.difference_percent>=0?'+':'')+fmt(d.peer.difference_percent,1)):'—','%',d.peer.status==='ok'?`${d.peer.peer_count}개교 비교`:'동일 조건 학교 부족')}</div><div class="callout">관리등급: <strong>${esc(d.screening.grade)}</strong> · ${esc(d.screening.reasons.join(' · '))}. 현장조사 전 원인을 확정하지 않습니다.</div><br>
  <div class="grid columns"><div class="grid"><article class="card"><div class="section-head"><h2>월별 에너지·탄소</h2><span class="legend">총 에너지 사용량</span></div>${lineChart(recent.map(x=>x.total_kwh))}<div class="bar-labels"><span>1월</span><span>6월</span><span>12월</span></div></article><article class="card"><div class="section-head"><h2>월별 데이터</h2><span class="hint">누락 시 수치 미표시</span></div><div class="table-wrap"><table><thead><tr><th>월</th><th>전기 kWh</th><th>가스 kWh</th><th>탄소 kgCO₂e</th><th>상태</th></tr></thead><tbody>${recent.map(x=>`<tr><td>${esc(x.month)}</td><td>${fmt(x.electricity_kwh)}</td><td>${fmt(x.gas_kwh)}</td><td>${fmt(x.kgco2e,1)}</td><td>${x.complete?pill('검증'):pill('확인 필요','bad')}</td></tr>`).join('')}</tbody></table></div></article></div>
  <div class="grid"><article class="card"><div class="section-head"><h2>학교 기본정보</h2></div><div class="facts"><div class="fact"><span>학교급</span><strong>${esc(s.level)}</strong></div><div class="fact"><span>지역</span><strong>${esc(s.district)}</strong></div><div class="fact"><span>연면적</span><strong>${fmt(s.area_m2)} ㎡</strong></div><div class="fact"><span>학생수</span><strong>${fmt(s.students)} 명</strong></div><div class="fact"><span>승인연도</span><strong>${esc(s.approval_year)}</strong></div><div class="fact"><span>주소</span><strong>${esc(s.address)}</strong></div></div></article><article class="card"><div class="section-head"><h2>학교–지번 연결</h2></div>${d.parcels.map(p=>`<div class="row"><div><strong>${esc(p.parcel_key)}</strong><div class="metric-sub">${esc(p.evidence)}</div></div>${pill(p.status==='confirmed'?'확인됨':'검토 중',p.status==='confirmed'?'ok':'bad')}</div>`).join('')}<div class="callout">학교 주소만으로 에너지 사용 지번을 확정하지 않습니다. 연결 근거와 검토 이력을 보존합니다.</div></article><article class="card"><div class="section-head"><h2>시설 및 개선이력</h2></div>${d.facilities.length?d.facilities.map(f=>`<div class="row"><strong>${esc(f.name)}</strong><span>설치 ${esc(f.installed_year)} · 교체 ${esc(f.replaced_year||'—')}</span></div>`).join(''):'<div class="empty">등록된 시설 정보가 없습니다.</div>'}${d.projects.map(p=>`<div class="row"><button class="link" data-project="${esc(p.id)}">${esc(p.name)}</button><span>${esc(p.completed_month)}</span></div>`).join('')}</article><article class="card"><div class="section-head"><h2>태양광 발전</h2><span class="hint">${d.solar?`${d.solar.covered_months}/12개월`:'설비 자료 없음'}</span></div>${d.solar?`<div class="row"><span>설비용량</span><strong>${fmt(d.solar.capacity_kw,1)} kW</strong></div><div class="row"><span>연간 발전량</span><strong>${d.solar.generation_kwh==null?'—':fmt(d.solar.generation_kwh/1000,1)+' MWh'}</strong></div><div class="row"><span>용량당 발전량</span><strong>${d.solar.specific_yield_kwh_per_kw==null?'—':fmt(d.solar.specific_yield_kwh_per_kw,0)+' kWh/kW'}</strong></div><div class="row"><span>확인된 자가소비량</span><strong>${d.solar.self_consumed_kwh==null?'—':fmt(d.solar.self_consumed_kwh/1000,1)+' MWh'}</strong></div>`:'<div class="empty">태양광 계측 자료가 없습니다.</div>'}</article></div></div>`;
  $('#school-select').addEventListener('change',e=>{chosenSchool=e.target.value;render()});
  document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{chosenProject=b.dataset.project;switchView('project')}));
}
async function project(){
  if (!projects.length) { view.innerHTML='<article class="card"><h2>시설개선 이력 대기</h2><div class="empty">교육지원청 사업 이력이 등록되면 전후 효과를 분석합니다.</div></article>'; return; }
  const d=await api(`/api/projects/${chosenProject}`);
  view.innerHTML=`<div class="selector-line"><label for="project-select">개선사업 선택</label><select id="project-select">${projects.map(p=>`<option value="${esc(p.id)}" ${p.id===chosenProject?'selected':''}>${esc(p.name)} · ${esc(p.completed_month)}</option>`).join('')}</select></div>${d.status!=='estimate'?`<article class="card"><h2>효과 추정 보류</h2><div class="empty">${esc(d.reasons.join(', '))}</div></article>`:`<div class="grid summary-grid">${card('기상보정 절감량',fmt(d.estimated_saving_kwh/1000,1),'MWh/년','12개월 관측기간 기준')}${card('추정 절감률',fmt(d.estimated_saving_percent,1),'%','사업 전 모델 대비')}${card('추정 탄소감축',fmt(d.estimated_carbon_saving_kgco2e==null?null:d.estimated_carbon_saving_kgco2e/1000,1),'tCO₂e/년',isDemo?'연도별 합성계수 기준':'승인된 적용계수 기준')}</div><div class="grid columns"><article class="card"><div class="section-head"><h2>사업 전·후 비교</h2><span class="hint">${esc(d.pre_period.join(' ~ '))} → ${esc(d.post_period.join(' ~ '))}</span></div>${['electricity','gas'].map(f=>`<div class="row"><strong>${f==='electricity'?'전기':'가스'}</strong><span>기상보정 예상 ${fmt(d.energy[f].weather_adjusted_baseline_kwh/1000,1)} → 관측 ${fmt(d.energy[f].observed_post_kwh/1000,1)} MWh</span></div>`).join('')}<div class="callout">${esc(d.caveat)}</div></article><article class="card"><div class="section-head"><h2>사업 정보</h2></div><div class="row"><span>사업 유형</span><strong>${esc(d.project.kind)}</strong></div><div class="row"><span>완료월</span><strong>${esc(d.project.completed_month)}</strong></div><div class="row"><span>사업비</span><strong>${fmt(d.project.cost_krw/100000000,2)} 억원</strong></div><div class="row"><span>사업비 / 연간 절감 kWh</span><strong>${fmt(d.cost_krw_per_annual_kwh_saved,0)} 원</strong></div></article></div>`}`;
  $('#project-select').addEventListener('change',e=>{chosenProject=e.target.value;render()});
}
async function quality(){
  const [data,reviews,neis,candidates]=await Promise.all([api('/api/quality'),api('/api/match-reviews'),api('/api/neis-reference'),api('/api/parcel-candidates')]);
  const candidateHtml=`<article class="card"><div class="section-head"><h2>주소에서 찾은 지번 후보</h2><span class="hint">${candidates.length}건 · 학교 시설대장 확인 전</span></div>${candidates.length?`<div class="table-wrap"><table><thead><tr><th>학교</th><th>도로명주소</th><th>지번주소</th><th>지번키</th><th>상태</th></tr></thead><tbody>${candidates.map(x=>`<tr><td>${esc(x.school_name)}</td><td>${esc(x.road_address)}</td><td>${esc(x.jibun_address)}</td><td>${esc(x.parcel_key)}</td><td>${pill(x.shared_candidate?'공유 후보':x.status==='pending'?'검토 대기':x.status==='rejected'?'제외':'검토됨',x.status==='pending'?'dim':x.status==='rejected'?'bad':'ok')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">나이스 도로명주소는 수집됐습니다. 주소정보 연계 후 지번 후보가 여기에 표시됩니다.</div>'}<div class="callout">주소 한 건으로 학교의 모든 부지와 계량기 범위가 확인되지는 않습니다. 후보는 확정 전 에너지 집계에 포함하지 않습니다.</div></article><br>`;
  view.innerHTML=`${neis.length?`<article class="card"><div class="section-head"><h2>나이스 학교 참조자료</h2><span class="hint">${neis.length}개교 · 시설대장 대조 전</span></div><div class="table-wrap"><table><thead><tr><th>학교코드</th><th>학교명</th><th>학교급</th><th>주소</th></tr></thead><tbody>${neis.map(x=>`<tr><td>${esc(x.school_code)}</td><td>${esc(x.name)}</td><td>${esc(x.level)}</td><td>${esc(x.address)}</td></tr>`).join('')}</tbody></table></div><div class="callout">학교코드와 주소는 참조용입니다. 연면적·학생수·복수 지번은 교육지원청 자료로 확인해야 합니다.</div></article><br>`:''}<article class="card"><div class="section-head"><h2>학교–지번 매칭 검증</h2><span class="hint">확정 지번만 학교 에너지에 합산</span></div><div class="table-wrap"><table><thead><tr><th>학교</th><th>지번키</th><th>상태</th><th>매칭 방법</th><th>근거</th><th>검토일</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.parcel_key)}</td><td>${pill(x.status==='confirmed'?'확정':x.status==='rejected'?'제외':'보류',x.status==='confirmed'?'ok':'bad')}</td><td>${esc(x.method)}</td><td>${esc(x.evidence)}</td><td>${esc(x.reviewed_at||'—')}</td></tr>`).join('')}</tbody></table></div><div class="callout">실제 적용 전에는 학교 시설대장과 지번·계량기 범위를 담당자가 대조해야 합니다. 미확정 지번이 있는 학교의 수치는 공개·비교에서 제외합니다.</div></article>${reviews.length?`<article class="card" style="margin-top:16px"><h2>검토 이력</h2><div class="table-wrap"><table><thead><tr><th>지번키</th><th>결정</th><th>검토자</th><th>근거</th><th>일시</th></tr></thead><tbody>${reviews.map(x=>`<tr><td>${esc(x.parcel_key)}</td><td>${esc(x.previous_status)} → ${esc(x.new_status)}</td><td>${esc(x.reviewer)}</td><td>${esc(x.evidence)}</td><td>${esc(x.reviewed_at)}</td></tr>`).join('')}</tbody></table></div></article>`:''}`;
  view.insertAdjacentHTML('afterbegin', candidateHtml);
}
async function education(){
  if (!schools.length) { view.innerHTML='<article class="card"><h2>교육용 자료 준비 중</h2></article>'; return; }
  const month=`${year()}-12`,d=await api(`/api/education/${chosenSchool}?year=${year()}&month=${month}`);
  view.innerHTML=`${schoolSelect()}${d.status==='ok'?`<div class="educard"><div class="eyebrow">우리 학교의 변화 · ${esc(d.month)}</div><h2>에너지를 아끼는 우리 학교</h2><div class="edu-grid"><div class="edu-stat"><span>이번 달 전기사용량</span><strong>${fmt(d.electricity_kwh)} <small>kWh</small></strong></div><div class="edu-stat"><span>지난해 같은 달보다</span><strong>${d.electricity_yoy_percent==null?'—':`${d.electricity_yoy_percent<0?'▼':'▲'} ${fmt(Math.abs(d.electricity_yoy_percent),1)}%`}</strong></div><div class="edu-stat"><span>태양광 발전량</span><strong>${d.solar_generation_kwh==null?'—':fmt(d.solar_generation_kwh)} <small>${d.solar_generation_kwh==null?'':'kWh'}</small></strong></div></div></div><div class="callout">태양광 탄소감축 수치는 자가소비량이 확인된 경우에만 산출합니다. ${d.solar_avoided_kgco2e==null?'현재 확인 가능한 감축 수치가 없습니다.':`이번 달 추정 대체량 ${fmt(d.solar_avoided_kgco2e,1)} kgCO₂e.`}</div>`:`<article class="card"><h2>공개 자료 준비 중</h2><div class="empty">학교·지번 또는 월별 데이터 검증이 완료되지 않았습니다.</div></article>`}`;
  $('#school-select').addEventListener('change',e=>{chosenSchool=e.target.value;render()});
}
const views={overview,priority,school,project,quality,education};
const titles={overview:'관내 에너지 현황',priority:'시설개선 현장확인 순서',school:'학교별 에너지 분석',project:'시설개선 효과분석',quality:'데이터 연결 검증',education:'생태전환교육 화면'};
async function render(){view.innerHTML='<div class="empty">데이터를 불러오는 중입니다.</div>';try{await views[currentView]()}catch(e){view.innerHTML=`<div class="card error">${esc(e.message)}</div>`}}
function switchView(next){currentView=next;$('#page-title').textContent=titles[next];document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===next));render()}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>switchView(n.dataset.view)));
$('#year').addEventListener('change',render);
Promise.all([api('/api/schools'),api('/api/projects'),api('/api/meta'),api('/api/neis-reference')]).then(([s,p,m,n])=>{
  schools=s;projects=p;neisSchools=n;
  isDemo=m.demo;
  if (schools.length) chosenSchool=schools[0].id;
  if (neisSchools.length) chosenReference=neisSchools[0].school_code;
  if (projects.length) chosenProject=projects[0].id;
  $('.side-note').innerHTML=m.demo?'<span class="dot"></span> 합성 시연 데이터<br><small>실제 학교·배출계수 아님</small>':'<span class="dot"></span> 실증 데이터 검증 중<br><small>누락값은 결과에서 제외</small>';
  const notice=$('.notice');
  notice.querySelector('strong').textContent=m.demo?'DEMO':'PoC';
  notice.querySelector('span').textContent=m.demo?
    '화면의 학교명·주소·사용량·배출계수는 모두 합성값입니다. 불완전한 학교는 합계에서 제외합니다.':
    '실증 데이터의 지번 매칭·계수·시설 이력을 검증 중입니다. 후보 지번 사용량은 잠정 조회치이며 확정 학교 합계는 별도로 표시합니다.';
  render();
}).catch(e=>view.textContent=e.message);


